on: [push]

jobs: 
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps: 
    - name: Hello world action steps
      id: hello
      uses: julzelements/hello-world-docker-action@v1
      with: 
        who-to-greet: 'Julz'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: secret check
      run: $I_LOVE_ROXIE && echo "I love roxie"
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v2